# Generated by Django 5.2.1 on 2026-05-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_avatar_url'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('red', 'Red'), ('blue', 'Blue')], default='yellow', max_length=10)),
                ('note_type', models.CharField(choices=[('personal', 'Personal'), ('team', 'Team')], default='personal', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.workspacemembership')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
                'indexes': [models.Index(fields=['workspace', 'note_type'], name='notes_quick_workspa_626cc8_idx'), models.Index(fields=['workspace', 'created_by'], name='notes_quick_workspa_b0e0b1_idx'), models.Index(fields=['workspace', 'is_pinned'], name='notes_quick_workspa_549c9c_idx')],
            },
        ),
    ]
