# Generated by Django 5.2.1 on 2026-05-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicknote',
            name='title',
        ),
        migrations.AlterField(
            model_name='quicknote',
            name='content',
            field=models.TextField(),
        ),
    ]
