# Generated by Django 5.2.1 on 2026-05-10 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('completion_at_start', models.PositiveSmallIntegerField(default=0)),
                ('completion_at_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('switch_note', models.TextField(blank=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.workspacemembership')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tasks.task')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DeveloperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('current_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.activitysession')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='accounts.workspacemembership')),
            ],
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['membership', 'started_at'], name='activity_ac_members_2a4d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['task', 'started_at'], name='activity_ac_task_id_aa7645_idx'),
        ),
    ]
