# Generated by Django 5.2.1 on 2026-05-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('activity', '0002_collaboration'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collaborationrequest',
            name='unique_collab_request',
        ),
        migrations.RemoveConstraint(
            model_name='taskcollaborator',
            name='unique_task_collaborator',
        ),
        migrations.RenameIndex(
            model_name='collaborationactivitylog',
            new_name='activity_co_task_id_2d806b_idx',
            old_name='activity_cal_task_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborationrequest',
            new_name='activity_co_target__7c71e5_idx',
            old_name='activity_cr_target_status_idx',
        ),
        migrations.RenameIndex(
            model_name='collaborationrequest',
            new_name='activity_co_task_id_744674_idx',
            old_name='activity_cr_task_status_idx',
        ),
        migrations.RenameIndex(
            model_name='taskcollaborator',
            new_name='activity_ta_task_id_1d17e5_idx',
            old_name='activity_tc_task_active_idx',
        ),
        migrations.AlterUniqueTogether(
            name='collaborationrequest',
            unique_together={('requester', 'target', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='taskcollaborator',
            unique_together={('task', 'member')},
        ),
    ]
